name: CI
on: push
env:
  APP_IMAGE_NAME: paths-backend/paths
  DB_IMAGE_NAME: paths-backend/paths-postgres
  BUILD_CACHE_IMAGE_NAME: paths-backend/paths-build-cache
  VAULT_KEY: common-dev/data/github-actions/project/paths-backend
  IMAGE_TAG: ${{ github.sha }}
  DATABASE_URL: postgres://postgres:postgres@localhost/kausal-paths
  REDIS_URL: redis://localhost:6379/0

jobs:
  build:
    name: Build
    runs-on: self-hosted
    env:
      POSTGRES_PASSWORD: foobar123
      EXTRA_PYPI_INDEX: ${{ secrets.EXTRA_PYPI_INDEX }}
      #DOCKER_BUILDKIT: 1
      #BUILDKIT_PROGRESS: plain
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Check for deployment branch
        if: startsWith(github.ref, 'refs/heads/deployment/')
        run: |
          echo "DEPLOYMENT_TYPE=$(echo ${{ github.ref }} | cut -d / -f 4)" >> $GITHUB_ENV

      - name: Import Secrets
        id: secrets
        uses: hashicorp/vault-action@v2
        with:
          url: ${{ secrets.VAULT_URL }}
          token: ${{ secrets.VAULT_TOKEN }}
          secrets: |
            ${{ env.VAULT_KEY }}/docker * | DOCKER_ ;

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log into Docker registry
        #if: env.DEPLOYMENT_TYPE
        uses: docker/login-action@v2
        with:
          registry: ${{ env.DOCKER_REPO }}
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      - name: Build and load Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: docker/app/Dockerfile
          push: true
          tags: ${{ env.DOCKER_REPO }}/${{ env.APP_IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          cache-from: type=registry,ref=${{ env.DOCKER_REPO }}/${{ env.BUILD_CACHE_IMAGE_NAME }}:cache
          cache-to: type=registry,ref=${{ env.DOCKER_REPO }}/${{ env.BUILD_CACHE_IMAGE_NAME }}:cache,mode=max,image-manifest=true

  test:
    name: Test
    runs-on: self-hosted
    services:
      postgres:
        image: postgres:15
        ports: ["5432:5432"]
        env:
          POSTGRES_DB: kausal-paths
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres

      redis:
        image: redis:6
        ports: ["6379:6379"]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        id: setup-python
        with:
          python-version: 3.11

      - name: Setup Virtual Environment
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install --upgrade pip

      - name: Install dependencies
        run: |
          source .venv/bin/activate
          pip install -r requirements.txt

      - name: Run Pytest
        run: |
          source .venv/bin/activate
          pytest .
