name: CI
on: push
env:
  PROJECT_ID: paths-backend

jobs:
  lint:
    uses: ./.github/workflows/reviewdog.yml

  build:
    uses: kausaldev/github-actions/.github/workflows/build-backend.yaml@main
    if: "${{ ! startsWith(github.ref, 'refs/heads/wip/') }}"
    secrets: inherit
    with:
      project_id: paths-backend

  test:
    needs: [build]
    uses: ./.github/workflows/test.yaml
    secrets: inherit
    with:
      docker_image_repo: ${{ needs.build.outputs.image }}
      docker_image_tag: ${{ needs.build.outputs.image_tag }}
      build_id: ${{ needs.build.outputs.build_id }}

  ui-e2e-test:
    needs: [build]
    uses: ./.github/workflows/ui-e2e-tests.yaml
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    with:
      product_id: paths
      instance_identifiers: sunnydale
      ui_repo: kausaldev/kausal-paths-ui
      ui_repo_ref: deployment/testing
      ui_image: "${{ vars.DOCKER_REGISTRY }}/paths-ui/paths-ui:latest"
      backend_image: "${{ needs.build.outputs.image }}:${{ needs.build.outputs.image_tag }}"
      build_id: "${{ needs.build.outputs.build_id }}"
      s3_endpoint: ${{ vars.BUILD_S3_ENDPOINT }}
      s3_bucket: ${{ vars.BUILD_S3_BUCKET }}

  deploy:
    needs: [build]
    uses: kausaldev/github-actions/.github/workflows/deploy.yaml@main
    secrets: inherit
    if: needs.build.outputs.deployment_env
    with:
      docker_image_repo: ${{ needs.build.outputs.image }}
      docker_image_tag: ${{ needs.build.outputs.image_tag }}
      project_id: paths-backend
      deployment_env: ${{ needs.build.outputs.deployment_env }}
