name: CI
on: push
env:
  PROJECT_ID: paths-backend

jobs:
  build:
    uses: kausaldev/github-actions/.github/workflows/build-backend.yaml@main
    secrets: inherit
    with:
      project_id: paths-backend

  test:
    needs: [build]
    uses: ./.github/workflows/test.yaml
    secrets: inherit
    with:
      docker_image_repo: ${{ needs.build.outputs.image }}
      docker_image_tag: ${{ needs.build.outputs.image_tag }}
      build_id: ${{ needs.build.outputs.build_id }}

  deploy:
    needs: [build]
    uses: kausaldev/github-actions/.github/workflows/deploy.yaml@main
    secrets: inherit
    if: needs.build.outputs.deployment_env
    with:
      docker_image_repo: ${{ needs.build.outputs.image }}
      docker_image_tag: ${{ needs.build.outputs.image_tag }}
      project_id: paths-backend
      deployment_env: ${{ needs.build.outputs.deployment_env }}
