name: reviewdog
on:
  pull_request:
  workflow_call:

jobs:
  reviewdog:
    name: reviewdog
    runs-on: ubuntu-latest
    permissions:
      checks: write
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Setup cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            .mypy_cache
          key: ${{ runner.os }}-${{ hashFiles('requirements-lint.txt') }}
      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
          cache: 'pip'
          cache-dependency-path: |
            requirements-lint.txt
      - name: Install dependencies
        run: python -m pip install -r requirements-lint.txt -r requirements.txt
      - name: Save cache
        uses: actions/cache/save@v4
        with:
          path: |
            ~/.cache/pip
          key: ${{ runner.os }}-${{ hashFiles('requirements-lint.txt') }}
      - name: Print env
        run:
          env

      - name: do diff
        if: github.event_name == 'push'
        run:
          echo ${{ github.event.before }}
          echo ${{ github.sha }}
          git diff --find-renames --submodule=diff ${{ github.event.before }} ${{ github.sha }}

      - uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: latest # Optional. [latest,nightly,v.X.Y.Z]
      - name: Run reviewdog
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          reviewdog -reporter=github-check -log-level=debug

